# Declare const variables
HEIGHT_SCREEN = 1280
WIDTH_SCREEN = 720
FPS = 60
VERSION = 1.0

ZOMBIE_WIDTH_HITBOX = 70
ZOMBIE_HEIGHT_HITBOX = 97
ZOMBIE_SPRITE_LENGTH = 7
ZOMBIE_CHANGE_STATE_TIME = 1 * FPS
ZOMBIE_STANDING_TIME = 1 * FPS