### General
WIDTH_SCREEN = 1280
HEIGHT_SCREEN = 720
FPS = 60
VERSION = 1.0

### Zombie
ZOMBIE_WIDTH_HITBOX = 70
ZOMBIE_HEIGHT_HITBOX = 97
ZOMBIE_SPRITE_LENGTH = 7
ZOMBIE_CHANGE_STATE_TIME = 1 * FPS
ZOMBIE_STANDING_TIME = 1 * FPS
SKY_LINE_Y = 200
ZOMBIE_MIN_SCALE = 0.25
ZOMBIE_MAX_SCALE = 1
# scale = a * (y) + b
SCALE_A = (ZOMBIE_MAX_SCALE - ZOMBIE_MIN_SCALE) / (HEIGHT_SCREEN - SKY_LINE_Y)
SCALE_B = ZOMBIE_MAX_SCALE - HEIGHT_SCREEN * SCALE_A
